---
- name: azure resources
  hosts: localhost
  gather_facts: no

  tasks:
    - name: instantiate azure resources with terraform
      terraform:
        project_path: "{{ playbook_dir }}"
        state: present

    - name: refresh the inventory
      meta: refresh_inventory

- name: gns3 components
  hosts: gns3

  vars_files:
    - vars/vars-gns3.yml
  
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes
 
  tasks:
    - name: create gns3 user
      user:
        name: gns3
        home: /opt/gns3
        system: yes
      become: yes

    - name: create source code directory for gns3 components
      file:
        path: "{{ src_dir }}"
        state: directory

    - import_tasks: tasks/duckdns.yml
    - import_tasks: tasks/openvpn.yml
    - import_tasks: tasks/i386-arch.yml
    - import_tasks: tasks/dynamips.yml
    - import_tasks: tasks/vpcs.yml
    - import_tasks: tasks/iouyap.yml
    - import_tasks: tasks/iol.yml
    - import_tasks: tasks/ubridge.yml
    - import_tasks: tasks/qemu.yml
    - import_tasks: tasks/libvirt.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/gns3.yml

  handlers:
    - name: restart openvpn
      service:
        name: openvpn-server@server
        state: restarted
      become: yes

    - name: restart gns3
      service:
        name: gns3
        state: restarted
      become: yes
...
